name: "WD-Forms"
author: "xxAROX"
description: "WaterdogPE form plugin"
main: "xxAROX.WDForms.WDForms"
version: "2.1.0"
website: "https://github.com/xxAROX"
contributors:
  - "https://github.com/Crasher508"
load: "STARTUP"
