name: Java CI with Maven

on:
  push:
    branches: [ "main","waterdog-2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: WD-Forms
          path: target/*.jar
